### PR TITLE
Flagtastrophe

### PR DESCRIPTION
**Pull request by ekg**
This implements a major rewrite of the command line interface to remove lots of rarely used options and focus on commonly used ones and clear documentation of them.

### CODE REVIEW

**Comment by AndreaGuarracino** [comment]
Tiny requests:

- Limit `-s` up to `10k` (and `-l` up to 30k) and `-P` up to ~100k (or a bit more) when running mapping+alignment. With higher values, show an `ERROR`, explaining that all values can be set without limitations with `-m, --approx-mapping`. Users can use `-m` to map with high `-s/-l/-P` values and then run `wfmash ... -i mappings.paf` to align them (if they want to).

- Avoid mixing mashmap/wfmash logging messages?
```shell
[wfmash] Warning: Detected single file all-vs-all mapping with no other options. Consider adding -L, --lower-triangular for efficiency.
[mashmap] Performing all-vs-all mapping including self mappings.
[wfmash] Estimated unique 15-mers: 8280852 (based on total reference size: 96419351 bp)
...
```

- Update MashMap version
```shell
[mashmap] MashMap v3.1.1
```

- Can we have a more compact list of the parameters (less rows)

```shell
[mashmap] Kmer size = 15
[mashmap] Sketch size = 39
[mashmap] Segment length = 1000 (read split allowed)
[mashmap] Block length min = 3000
[mashmap] Chaining gap max = 2000
[mashmap] Max mapping length = 50000
[mashmap] Mappings per segment = 1
[mashmap] Percentage identity threshold = 95%
[mashmap] Do not skip self mappings
[mashmap] Hypergeometric filter w/ delta = 0 and confidence 0.999
[mashmap] Mapping output file = /home/guarracino/Desktop/Garrison/impg/wfmash-Xopw2G
[mashmap] Filter mode = 1 (1 = map, 2 = one-to-one, 3 = none)
[mashmap] Execution threads  = 10
```

**Comment by AndreaGuarracino** [comment]
`--read-index` instead od `--index`, for symmetry with `--write-index`
```shell
  Indexing:
    -W[FILE], --write-index=[FILE]   build and save index to FILE
    -i[FILE], --index=[FILE]         use pre-built index from FILE
    -b[SIZE], --batch=[SIZE]         target batch size for indexing [4G]
    -w[INT], --sketch-size=[INT]     sketch size for MinHash [auto]
    -k[INT], --kmer-size=[INT]       k-mer size [15]

**Comment by ASLeonard** [comment]
Another nitpick, but after this PR, running `wfmash` or `wfmash -h` prints the help message, but running `wfmash -m` or `wfmash -a` or almost any other parameter will print instead

```
[wfmash] Estimated unique 15-mers: 0 (based on total reference size: 0 bp)
[mashmap] MashMap v3.1.1
[mashmap] Reference = []
[mashmap] Query = []
[mashmap] Kmer size = 15
[mashmap] Sketch size = 137
[mashmap] Segment length = 1000 (read split allowed)
[mashmap] Block length min = 3000
[mashmap] Chaining gap max = 2000
[mashmap] Max mapping length = 50000
[mashmap] Mappings per segment = 1
[mashmap] Percentage identity threshold = 70%
[mashmap] Do not skip self mappings
[mashmap] Hypergeometric filter w/ delta = 0 and confidence 0.999
[mashmap] Mapping output file = /dev/stdout
[mashmap] Filter mode = 1 (1 = map, 2 = one-to-one, 3 = none)
[mashmap] Execution threads  = 1
[SequenceIdManager::buildRefGroups] ERROR: No sequences indexed!
```

target.fa is a "required" argument, but wfmash doesn't seem to actually require/check that and the error only arises later during the indexing step. Expected behaviour would be to get the help message if you do not pass required arguments.

**Comment by AndreaGuarracino** [comment]
Update the README accordingly to all the new changes. For example, in the example we should not show -s 20k when we align sequences, while we should show an example where users can specify high -s/-P values if they use `-m`.

**Pull request merged**
