### PR TITLE
[WIP] Replace minimizers with minmers

### PR DESCRIPTION
**Pull request by bkille**

### CODE REVIEW

**Comment by ekg** [comment]
I posted this in matrix chat, but in case you aren't checking.

I get a segfault with the following test:

```
wget http://hypervolu.me/~erik/yeast/cerevisiae.pan.fa.gz
samtools faidx cerevisiae.pan.fa.gz
gdb wfmash -ex 'r -s 5000 -p 90 -n 6 cerevisiae.pan.fa.gz >x.paf'
```

This results in:

```
Thread 2 "wfmash" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff2bff640 (LWP 162285)]
0x00007ffff6da35ce in std::_Rb_tree_decrement(std::_Rb_tree_node_base*) () from /lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff6da35ce in std::_Rb_tree_decrement(std::_Rb_tree_node_base*) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00005555556f9f23 in std::_Rb_tree_iterator<std::pair<unsigned int const, std::pair<skch::MinmerInfo, unsigned long> > >::operator-- (this=<synthetic pointer>)
    at /usr/include/c++/11/bits/stl_tree.h:302
#2  std::__advance<std::_Rb_tree_iterator<std::pair<unsigned int const, std::pair<skch::MinmerInfo, unsigned long> > >, long> (__n=0, Python Exception <class 'gdb.error'>: value has been optimized out
__i=<synthetic pointer>)
    at /usr/include/c++/11/bits/stl_iterator_base_funcs.h:169
#3  std::advance<std::_Rb_tree_iterator<std::pair<unsigned int const, std::pair<skch::MinmerInfo, unsigned long> > >, long> (__n=-1, Python Exception <class 'gdb.error'>: value has been optimized out
__i=<synthetic pointer>)
    at /usr/include/c++/11/bits/stl_iterator_base_funcs.h:206
#4  std::prev<std::_Rb_tree_iterator<std::pair<unsigned int const, std::pair<skch::MinmerInfo, unsigned long> > > > (__n=1, __x=...)
    at /usr/include/c++/11/bits/stl_iterator_base_funcs.h:230
#5  skch::CommonFunc::addMinmers<skch::MinmerInfo> (minmerIndex=std::vector of length 4618, capacity 8192 = {...}, seq=<optimized out>, len=<optimized out>, 
    kmerSize=<optimized out>, windowSize=<optimized out>, alphabetSize=<optimized out>, sketchSize=<optimized out>, seqCounter=<optimized out>)
    at /home/erik/wfmash/src/map/include/commonFunc.hpp:415
#6  0x00005555556fcfd3 in skch::Sketch::buildHelper (input=0x607000000b80, this=0x7fffffffc8b0) at /home/erik/wfmash/src/map/include/winSketch.hpp:199
#7  skch::Sketch::build()::{lambda(skch::InputSeqContainer*)#1}::operator()(skch::InputSeqContainer*) const (e=0x607000000b80, __closure=<optimized out>)
    at /home/erik/wfmash/src/map/include/winSketch.hpp:140
#8  std::__invoke_impl<std::vector<skch::MinmerInfo, std::allocator<skch::MinmerInfo> >*, skch::Sketch::build()::{lambda(skch::InputSeqContainer*)#1}&, skch::InputSeqContainer*>(std::__invoke_other, skch::Sketch::build()::{lambda(skch::InputSeqContainer*)#1}&, skch::InputSeqContainer*&&) (__f=...) at /usr/include/c++/11/bits/invoke.h:61
#9  std::__invoke_r<std::vector<skch::MinmerInfo, std::allocator<skch::MinmerInfo> >*, skch::Sketch::build()::{lambda(skch::InputSeqContainer*)#1}&, skch::InputSeqContainer*>(skch::Sketch::build()::{lambda(skch::InputSeqContainer*)#1}&, skch::InputSeqContainer*&&) (__fn=...) at /usr/include/c++/11/bits/invoke.h:114
#10 std::_Function_handler<std::vector<skch::MinmerInfo, std::allocator<skch::MinmerInfo> >* (skch::InputSeqContainer*), skch::Sketch::build()::{lambda(skch::InputSeqContainer*)#1}>::_M_invoke(std::_Any_data const&, skch::InputSeqContainer*&&) (__functor=..., __args#0=<optimized out>) at /usr/include/c++/11/bits/std_function.h:290
#11 0x00005555556212ff in std::function<std::vector<skch::MinmerInfo, std::allocator<skch::MinmerInfo> >* (skch::InputSeqContainer*)>::operator()(skch::InputSeqContainer*) const
    (__args#0=<optimized out>, this=0x7fffffffb930) at /usr/include/c++/11/bits/std_function.h:590
#12 ThreadPool<skch::InputSeqContainer, std::vector<skch::MinmerInfo, std::allocator<skch::MinmerInfo> > >::thread (arg=0x7fffffffb920)
--Type <RET> for more, q to quit, c to continue without paging--
    at /home/erik/wfmash/src/map/include/ThreadPool.hpp:253
#13 0x00007ffff6a42b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#14 0x00007ffff6ad4a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

I've built wfmash with debugging flags via `cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug && cmake --build build -- -j 16`.

**Comment by ekg** [comment]
It looks like the problem is with this call:

```
                // Did we incorporate a previously hashed kmer into the sketch?                                                                                                    
                auto& sth_mi = std::prev(piv.p)->second.first;
```

**Comment by bkille** [comment]
Thanks for posting this. Seems like my bookkeeping of the pivot pointer is off. If I reset pivot at the end of each iteration via 
```
piv.p = std::next(sortedWindow.begin(), std::min<int>(sortedWindow.size(), sketchSize));
```

I no longer get a segfault. 

I'll take a crack at this over the weekend and update next week.

**Comment by bkille** [comment]
Update, seems like the pointer bookkeeping actually might be okay, the issue is that the sorted window of kmers is somehow empty at this point, which causes the segfault. Looking into that now.

**Comment by bkille** [comment]
# An update on the minmer-sketch PR:

* Fixed the bug caused by long regions of `N`. The tldr; is that since we ignore kmers that have the same reverse complement, the sketch ended up being empty for those regions which was an uncaught edge-case. That being said, I think the reference-indexing part of the PR could still be cleaned up a bit. Its much more complicated than I feel it should be

* I added in another optimization, which caused some delays, but the speedup appears to be pretty significant. I'll try to explain it here. Before, the L1 filtering step would identify candidate super-windows for which to compute the true MinHash distance for each subwindow by using an upper bound on the sketch intersection size. In the original MashMap, these super-windows were super loose, and resulted in (1) large L1 windows and (2) lots of L1 windows. This was somewhat resolved in my implementation for 2 reasons: (1) We compute the true sketch intersection for each position in the reference and not an upper bound and (2) Instead of the cutoff being any window above the minimum intersection threshold, it was any window which was at most some distance away from the best window for that read. This greatly reduced the number of windows (as seen by the reduction in RAM (100gb to 10gb for the pairwise human alignment case). 

    If you trace the intersection size as you slide the read across the reference, though, you'll notice that for most optimal MinHash mappings, the position is a local optimum wrt the intersection size. i.e.  the intersection size for a sketch of size S will be ... S-2, S-1, S, S-1, S-2, ... This means that instead of returning large ranges from the L1 filter, we can return local optimums. I've implemented this in the PR as well, and it led to much better scaling wrt the sketch size S, as it results in significantly less computations of the sliding window MinHash in the L2 filter.

* I set up some benchmarks to compare against the master branch wfmash. I'll paste some of the highlights below.  The methodology is pretty straightforward, I just ran wfmash with T2T as the ref and HG02257 as the query. I'm running w/ a bunch of parameter combinations, but the results below are for a min-ANI of 90, one mapping/segment, segment length of 5000. The sketch size for my implementation was set to 40, which results in 1.07x as many minmer windows as minimizers, and 0.68x as many unique minmer seeds as minimizer seeds. I've also pasted the results w/ sketch size of 80, which leads to 2x as many minmer windows as minimizers and 1.29x as many unique seeds. For the difference of Blast ANI per contig, this was only computed for contigs which had mappings from both the minmer and minimizer runs. 

## Runtime for ANI cutoff 90%
Minimizer: `19161.75` seconds
Minmer (SS=80):  `7447.84` seconds --> 2.57x speedup
Minmer (SS=40):  `6062.74` seconds --> 3.16x speedup

Its worth noting that for an ANI cutoff of 85%, the minmer version completed in `8766.44` seconds, whereas the minimizer version is at 280,800 seconds and still running (>32x speedup). 

## Sketch size 40, ANI cutoff 90%
image
```
DescribeResult(nobs=306, minmax=(-1187679.999999996, 728583.9999999938), mean=-19448.754901960838, variance=23810503591.641327, skewness=-2.9239330333935007, kurtosis=20.007420113731545)
```

image
```
DescribeResult(nobs=306, minmax=(-1.0, 1.0), mean=-0.00912511783331557, variance=0.050468908553820156, skewness=-0.5652672085985005, kurtosis=10.863372954544896)
```

image
```
DescribeResult(nobs=201, minmax=(-0.07856167875232789, 0.1536294613020831), mean=-0.0005339915681597056, variance=0.0004980718453878337, skewness=1.851519047732779, kurtosis=15.991230075017555)
```

image
```
Minmer ANI stats: DescribeResult(nobs=678, minmax=(0.43586857142857144, 0.9997532962363971), mean=0.8792622210316013, variance=0.016685884860913717, skewness=-0.9380019533422141, kurtosis=-0.08544188600734914)
Minimizer ANI stats: DescribeResult(nobs=709, minmax=(0.3908643694685296, 0.9997551020408163), mean=0.8757406770203197, variance=0.016477462551006832, skewness=-0.9352387606016186, kurtosis=0.08484933112655879)
```

## Sketch size 80, ANI cutoff 90%
image
```
DescribeResult(nobs=306, minmax=(-1077344.0000000002, 776479.9999999962), mean=-22881.86601307196, variance=27275447598.726254, skewness=-2.454435111331431, kurtosis=16.47738473755853)
```

image
```
DescribeResult(nobs=306, minmax=(-1.0, 1.0), mean=-0.02132856256673958, variance=0.04405283974269678, skewness=-1.197368858122348, kurtosis=14.200351474646375)
```

image
```
DescribeResult(nobs=203, minmax=(-0.12935575504179642, 0.2925347513758688), mean=0.0020941515904597937, variance=0.0010241161151587103, skewness=4.568736909611025, kurtosis=38.60433102383641)
```

image
```
Minmer ANI stats: DescribeResult(nobs=663, minmax=(0.4445217391304348, 0.9997551020408163), mean=0.8851643910701313, variance=0.01558451197123758, skewness=-0.9924514914457923, kurtosis=0.05291537431566695)
Minimizer ANI stats: DescribeResult(nobs=709, minmax=(0.3908643694685296, 0.9997551020408163), mean=0.8757406770203197, variance=0.016477462551006832, skewness=-0.9352387606016186, kurtosis=0.08484933112655879)
```

**Comment by subwaystation** [comment]
:fire:

**Comment by ekg** [comment]
1/50 is something like setting `wfmash -w 50` on the master, right?

**Comment by bkille** [comment]
> 1/50 is something like setting `wfmash -w 50` on the master, right?

1/50 would lead to a sketch size of 100 for the default segment length. I have some corresponding minimizer `w` values in a dictionary here:

```
# For L=5000
sketchSize_to_minimizerW = {50: 172.0,
 100: 89.0,
 150: 60.0,
 200: 45.0,
 300: 30.0,
 400: 23.0,
 500: 18.0,
 600: 15.0,
 700: 13.0,
 800: 11.0,
 900: 10.0,
 1000: 9.0}
```

That being said, I think I should change the default sketch size to 1/25.

**Pull request closed without merging**
